### ISSUE TITLE
de-obfuscate all code in this package

### ISSUE THREAD

**Issue by zsunberg** [sisl/RedPen.jl#2]
It seems like all of the code in this package (e.g. .sbin, .svbin) could be de-obfuscated, making it easier to maintain and share. Instead of obfuscating the client and server code, it makes more sense to me to just obfuscate the evaluation code and the message sent back to the server.

**Comment by mossr** [comment]
Closed via e573fbd649ced3e86cf80cbca933d3b5e74dad1d
